describe("capsium.semver", function()
  local semver = require "capsium.semver"

  describe("parse", function()
    it("parses plain and v-prefixed versions", function()
      local v = assert(semver.parse("1.2.3"))
      assert.equals(1, v.major)
      assert.equals(2, v.minor)
      assert.equals(3, v.patch)

      local v2 = assert(semver.parse("v0.1.0"))
      assert.equals(0, v2.major)
    end)

    it("tolerates pre-release and build suffixes", function()
      assert.is_not_nil(semver.parse("1.2.3-alpha.1"))
      assert.is_not_nil(semver.parse("1.2.3+build.5"))
      assert.is_not_nil(semver.parse("1.2.3-rc.1+build"))
    end)

    it("rejects non-semver input", function()
      assert.is_nil(semver.parse("1.2"))
      assert.is_nil(semver.parse("1.2.3.4"))
      assert.is_nil(semver.parse("abc"))
      assert.is_nil(semver.parse(nil))
      assert.is_nil(semver.parse("1.2.3x"))
    end)
  end)

  describe("compare", function()
    it("orders by the numeric triple", function()
      assert.equals(-1, semver.compare("1.2.3", "1.2.4"))
      assert.equals(0, semver.compare("1.2.3", "1.2.3"))
      assert.equals(1, semver.compare("2.0.0", "1.9.9"))
      assert.equals(-1, semver.compare("0.9.9", "0.10.0"))
    end)

    it("errors on non-semver input", function()
      local cmp, err = semver.compare("1.2.3", "nope")
      assert.is_nil(cmp)
      assert.is_truthy(tostring(err):find("non%-semver"))
    end)
  end)

  describe("satisfies", function()
    it("matches exact versions", function()
      assert.is_true(semver.satisfies("1.2.3", "1.2.3"))
      assert.is_true(semver.satisfies("1.2.3", "=1.2.3"))
      assert.is_false(semver.satisfies("1.2.4", "1.2.3"))
    end)

    it("matches wildcards", function()
      assert.is_true(semver.satisfies("1.2.3", "1.x"))
      assert.is_true(semver.satisfies("1.2.3", "1.2.x"))
      assert.is_true(semver.satisfies("1.2.3", "1.2"))
      assert.is_true(semver.satisfies("1.2.3", "1"))
      assert.is_false(semver.satisfies("1.3.0", "1.2.x"))
      assert.is_false(semver.satisfies("2.0.0", "1.x"))
    end)

    it("matches comparators", function()
      assert.is_true(semver.satisfies("1.2.3", ">=1.0.0"))
      assert.is_true(semver.satisfies("1.0.0", ">=1.0.0"))
      assert.is_false(semver.satisfies("0.9.9", ">=1.0.0"))
      assert.is_true(semver.satisfies("1.0.1", ">1.0.0"))
      assert.is_true(semver.satisfies("0.9.0", "<1.0.0"))
      assert.is_true(semver.satisfies("2.0.0", "<=2.0.0"))
    end)

    it("matches caret ranges", function()
      assert.is_true(semver.satisfies("1.4.7", "^1.2.3"))
      assert.is_false(semver.satisfies("2.0.0", "^1.2.3"))
      assert.is_false(semver.satisfies("1.2.2", "^1.2.3"))
      -- 0.x caret rules
      assert.is_true(semver.satisfies("0.2.5", "^0.2.3"))
      assert.is_false(semver.satisfies("0.3.0", "^0.2.3"))
      assert.is_true(semver.satisfies("0.0.3", "^0.0.3"))
      assert.is_false(semver.satisfies("0.0.4", "^0.0.3"))
    end)

    it("matches tilde ranges", function()
      assert.is_true(semver.satisfies("1.2.9", "~1.2.3"))
      assert.is_false(semver.satisfies("1.3.0", "~1.2.3"))
      assert.is_false(semver.satisfies("1.2.2", "~1.2.3"))
    end)

    it("ANDs space-separated comparators", function()
      assert.is_true(semver.satisfies("1.5.0", ">=1.0.0 <2.0.0"))
      assert.is_false(semver.satisfies("2.5.0", ">=1.0.0 <2.0.0"))
      assert.is_false(semver.satisfies("0.5.0", ">=1.0.0 <2.0.0"))
    end)

    it("matches any version with *", function()
      assert.is_true(semver.satisfies("0.0.1", "*"))
      assert.is_true(semver.satisfies("9.9.9", "*"))
    end)
  end)

  describe("newest_satisfying", function()
    it("picks the newest satisfying version", function()
      local versions = { "1.0.0", "1.1.0", "2.0.0", "0.9.0" }
      assert.equals("1.1.0",
                    semver.newest_satisfying(versions, ">=1.0.0 <2.0.0"))
      assert.equals("2.0.0", semver.newest_satisfying(versions, ">=1.0.0"))
      assert.equals("0.9.0", semver.newest_satisfying(versions, "<1.0.0"))
      assert.is_nil(semver.newest_satisfying(versions, ">=3.0.0"))
      assert.is_nil(semver.newest_satisfying({}, "*"))
    end)
  end)
end)
