name: tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Lua Unit Tests (Busted)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lua-version: ['5.1', '5.2', '5.3', '5.4', 'luajit']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Lua ${{ matrix.lua-version }}
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.lua-version }}

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install dependencies from rockspec
        run: |
          luarocks make capsium-dev-1.rockspec --only-deps

      - name: Install test dependencies
        run: |
          luarocks install busted
          luarocks install luacov

      - name: Run Busted tests
        run: |
          busted --verbose --coverage

      - name: Generate coverage report
        run: |
          luacov
          cat luacov.report.out

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.lua-version }}
          path: |
            luacov.report.out
            luacov.stats.out
        if: always()
