name: test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  test:
    name: Test with OpenResty
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests
        run: bundle exec rake ci

      - name: RSpec Report
        uses: SonicGarden/rspec-report-action@v6
        with:
          json-path: tmp/rspec_results.json
          title: '# :test_tube: RSpec Test Results'
        if: always()
